### PR TITLE
ResXResourceManager: Prevent adding BOM character when saving Unicode…

### PR DESCRIPTION
**Pull request by haunguyen84**
https://github.com/tom-englert/ResXResourceManager/compare/master...haunguyen84:master#diff-efd2fa95ee6fd3559d6f8d6fe345471a

### CODE REVIEW

**Comment by taoyouh** [comment]
Does it remove the BOM from files that already have one? If yes, I think this change requires more discussion before the merge.

**Comment by haunguyen84** [comment]
> 
> 
> Does it remove the BOM from files that already have one? If yes, I think this change requires more discussion before the merge.

Yes, it will remove the BOM from files which already had one.

**Comment by haunguyen84** [comment]
Hi @tom-englert ,
I have tried to build and install this change as an extension in VS Studio. But it cannot be loaded correctly because of the package. However, it works well with standalone version.
So could you please do me a favor that you build an extension version of this change and send it to me by email?
Thanks a lot.
Hau Nguyen.

**Comment by tom-englert** [comment]
@haunguyen84 
- I've updated the CI-build to publish the artifacts also for CI-Builds, so staring with the next build you should be able to download them there.
- I have committed a fix yesterday, maybe you just have to rebase your branch.

**Comment by haunguyen84** [comment]
Hi @tom-englert ,
I have pulled your changes. It still has error
image
Could you please help to check it?
Thanks!

**Comment by tom-englert** [comment]
How would you expect me to read a log file that is on your computer? (But don't post the log file here, just read it!)
What happens if you just debug your extension?

**Comment by tom-englert** [comment]
BTW, this shows still "Rebase and merger", so you're not on top of master.

**Comment by haunguyen84** [comment]
> 
> 
> How would you expect me to read a log file that is on your computer? (But don't post the log file here, just read it!)
> What happens if you just debug your extension?

<description>CreateInstance failed for package [VSPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.&#x000D;&#x000A;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.3, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;   at tomenglertde.ResXManager.VSIX.VSPackage..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Could not load file or assembly &apos;TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.3, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.3, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2&apos;&#x000D;&#x000A;   at tomenglertde.ResXManager.VSIX.VSPackage..ctor()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>

**Comment by haunguyen84** [comment]
> 
> 
> BTW, this shows still "Rebase and merge", so you're not on top of master.

Because I am using VS2017, so there are some irrelevant changes.
Btw, I already rebased your master branch into this branch.
Thanks!

**Comment by haunguyen84** [comment]
Hi @tom-englert ,
Could you please do me a favor just a release version based on my change and send it to me?
Thanks a lot!

**Comment by tom-englert** [comment]
@haunguyen84 just download the ci build

**Comment by haunguyen84** [comment]
> just download the ci build

Dear @tom-englert ,
I downloaded and tested successfully:).

Thanks a lot!
Hau Nguyen.

**Comment by taoyouh** [comment]
I don't agree with this PR. It doesn't "prevent adding BOM" but "removes the BOM that are already there".

**Comment by tom-englert** [comment]
Superseded by 472a534

**Pull request closed without merging**
