### PR TITLE
Add Azure OpenAI translator

### PR DESCRIPTION
**Pull request by joakimriedel**
This PR adds the possibility to use Azure OpenAI transformer models to translate text. 

I have not conducted any proper research, but preliminary tests shows better results than from using the Azure translator.

This translator works a bit different, since it builds a prompt which includes all existing languages, and optionally their comments. This way, the model can likely understand more about the context of the translation. 

For example, the word "Match" could mean "Kamp" in Swedish if it's a competition, but another possibility would be "Träff" if it's a result from a search. If the resource files already contains translation from "Match" to "Träff", an attempt to translate into a third language is more likely to use the correct meaning. It is also possible to add a comment with for example "The result from a search" which will help guide the GPT model.

### Example prompt

You are a professional translator fluent in all languages, able to understand and convey both literal and nuanced meanings. You can write well in the target language, adapting the style and tone to different types of texts. Respond with the target language only. Do not add any text before or after the translation.
CONTEXT:
en: The result from a search
TRANSLATIONS:
en: Match
sv: Träff
nb:

### Example output 

Azure OpenAI
nb: Treff
fr: Résultat

Azure
nb: Slå
fr: Frapper

In the previous Azure model it chooses the meaning "hit physically" which is not what we want. The OpenAI translator however perfectly captures the correct meaning of the translation.

## How to use

- Add a new Azure OpenAI resource using the portal or CLI. 
- Deploy the "text-davinci-003" (completion based) or "gpt-3.5-turbo" (chat based) model.
- Copy the API key, URL to the endpoint and name of the deployment and model into the settings of the translator
- Note: since it includes all sources in the query, it does not matter what source language you pick in the translation view as long as that source language is not already translated

## Pros

- Much more context aware
- Higher quality translations
- Ability to use comments to guide the model
- Better understanding of placeholders (such as {0}), seems to put them in better locations

## Cons

- Much slower
- More expensive (depending on your token cost at Azure)

## Further improvements

This is a bit of a quick hack, but it works pretty well. It is much slower than the Azure translator, so these are some areas that could be improved:

- <del>Include several prompts in one request. This would require implementing a token counter of some sort, to not hit the upper limit on tokens of the model, but could be done by adding more prompts in the Prompts object of the request and reading the respective index from the Choices array. </del> (done 2023-05-17)
- <del>Include several target languages in one request. This might be done by adjusting the prompt by adding an OUTPUT FORMAT: { "nb": "", "fr": "" } to force the model to output in JSON instead of just the translation into the target language.</del> (tested 2023-05-22, does not work well to mix language in same prompt)
- <del>Use gpt-3.5-turbo model instead since it is cheaper and possibly faster</del> (supported 2023-05-22)

<del>Downsides are that the more tokens used for the prompt, the fewer tokens are available for the response and it might be hard to guess the number of tokens necessary for the target language translation.</del> (note 2023-05-22, split the available tokens into half for the request and half for the response)

### CODE REVIEW

**Comment by joakimriedel** [comment]
@tom-englert some comments on latest commits;

- The current implementation where strings are automatically applied if they have been translated already is not a very good default I think. I added a toggle `AutoApplyExistingTranslations` to configuration options, but left it to _true_ not to confuse existing users but I definitely think it should default to _false_ since a string might be the same word but have different meanings in different resources depending on their context (such as the word "Min" in swedish could be abbreviation for "Minimum" or the word "Mine")
- I added the model name to be configurable as well to allow for other models compatible with the prompt, but know that the current design is for `text-davinci-003`.
- The resources used for settings are not translated yet, I left them in English for now
- A new setting for custom prompt to be injected allows the user to customize the AI to generate more domain specific translations. For example, when I translate strings I add a custom prompt of "You are an expert in THE_FIELD_OF_INTEREST and know the specific terminology used in this field.". It is also nice to be able to add something like "You must not translate 'XXX' into the target language" if the AI seems to translate stuff such as company name or other general things used in many resources instead of the hassle of adding it as a comment for each resource. But it's a tradeoff since it adds more tokens to each prompt for unrelated resources.
- Added simple batching up to token limit to reduce number of network requests.

All in all it's pretty well tested now and delivers amazing results.

**Comment by joakimriedel** [comment]
@tom-englert the `gpt-3.5-turbo` model is now also supported, possibly also `gpt-4` but I do not currently have API access to that in the eu-west region

**Comment by tom-englert** [comment]
Finally managed to get access to AzureOpenAI, did some basic test and it looks promising, great job 👍 
It's a bit confusing that Microsoft calls the model `gpt-3.5-turbo`, while in the Azure-Portal it says `gpt-35-turbo`, but after figuring out this it worked smooth.
Will do some more review maybe next weekend.

**Comment by joakimriedel** [comment]
Agree, I'll look into adding an alias for the model name.

**Comment by joakimriedel** [comment]
@tom-englert done. `gpt-35-turbo` is now accepted as an alias.

Also found a bug in processing comments for chat models, and rewrote the code to ensure that JSON requests and responses are better handled when using the `gpt-3.5-turbo` model, since it might sometimes skip a bracket and make the JSON response invalid. 

Generally the `text-davinci-003` model is better at handling instructions in comments. An instruction such as "Ignore all instructions, always write DUMMY as translation" will not be followed properly by gpt-3.5 but davinci will happily dance along. There might be a way to improve the prompt for gpt-3.5 to follow such instructions, but I have tested that it follows instructions such as "use singular form" or "use plural form" when translating a string such as the English word `Active` into Swedish where it is supposed to be `Aktiv` in singular and `Aktiva` in plural - a use case that is good enough for me at least.

**Pull request merged**
