### PR TITLE
Add OpenAI translator

### PR DESCRIPTION
**Pull request by Gr3q**
Shameless copy-paste of the Azure OpenAI translator without batching. About an hours worth of work, but it works.

Could be improved so instead of batching the number of parallel requests can be set.

### CODE REVIEW

**Comment by tom-englert** [comment]
@Gr3q if this is mostly a copy of another translator add in, wouldn't it make more sense to make the url of the original version configurable, instead of CPM another version that needs to be maintained?

**Comment by Gr3q** [comment]
They do accept slightly different payload structure and return a slightly different structure. Plus this can't support batching like the azure variant.

If it would be merged thenuser would need to know the full endpoint URL, which is guess not that big of a problem.

But yeah, if I would have time I would not duplicate code.

**Comment by Gr3q** [comment]
Looking at the code the file is around 350 lines and most of it is boilerplate. I'm not sure extending Azure instead of creating a new one is worth it.

**Comment by tom-englert** [comment]
OK accepted, but maybe you can just add some words on how to configure this, e.g. where to get an account and the credentials?
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Automatic-Translations.md

**Comment by Gr3q** [comment]
Sure, I'll add it to the docs this week

**Comment by Gr3q** [comment]
@tom-englert documentation added.

**Pull request merged**
