### PR TITLE
Add VSIX support for arm64

### PR DESCRIPTION
**Pull request by joakimriedel**

### CODE REVIEW

**Comment by tom-englert** [comment]
Looks straight forward, 👍

**Comment by tom-englert** [comment]
Fixes #552

**Comment by tom-englert** [comment]
@joakimriedel just realized that `VSIX.Compatibility.arm64.csproj` is identical to `VSIX.Compatibility.x64.csproj` 

since both are `AnyCPU` there should be no need to have two of them.

Maybe you can verify this, since I don't have an ARM platform available.

**Comment by joakimriedel** [comment]
@tom-englert this looks like an oversight on my part. On .NET Framework, I know AnyCPU will run emulated (hence slower) on ARM64. For .NET (Core) and AnyCPU though, I know it will run native ARM64 during JIT, but I am not sure that would be enabling all the ARM64 optimizations. I tried searching for some post on this, but could not find anything that would support either. I think the safe bet would be to target ARM64 and not AnyCPU.

**Comment by tom-englert** [comment]
That won't give you much benefit, since 95% of the code is Any CPU, and this compatibility assembly is only a thin abstraction layer of the VS API

**Comment by joakimriedel** [comment]
@tom-englert I see. I did not go in detail on how the build is setup. Still, if it is not too much to maintain, having a separate target would assist in conveying multitargeting for future authors and a first step for future arm64 optimizations as well. Either way, I'd be happy to assist in testing on my hardware if necessary.

**Comment by tom-englert** [comment]
The VSIX format does not support packing multiple binaries per platform, so you would need to create a new VSIX package with a different ID that contains binaries compiled as arm64 to get real arm64 support.

**Comment by joakimriedel** [comment]
Aha. I have not (yet) authored a VSIX, so thanks for clarifying this. Please point me in a direction on how to build and install a VSIX from source, and I can test your patch.

**Comment by tom-englert** [comment]
Just build the solution, and look for the .vsix file in the bin folder

**Pull request merged**
