### PR TITLE
Fix #357 Add scroll if too many languages

### LINKED ISSUE #357: Too many languages, list does not scroll
When there are too many languages to fit on the screen, it's impossible to select languages because the dropdown does not scroll.

image

Is there another way to select the languages I want to see?

### PR DESCRIPTION
**Pull request by herizzon**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=380) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=380) before we can accept your contribution.<br/><br/>:x: herizzon [sign now](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=380)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/ResXResourceManager?pullRequest=380) it.</sub>

**Comment by tom-englert** [comment]
:+1: 😄

**Comment by tom-englert** [comment]
@herizzon P.S. Grids are very hard to maintain, I try to avoid them whenever possible: https://github.com/dotnet/ResXResourceManager/commit/527029773bb070153bac584b10407409223a77cf

**Comment by herizzon** [comment]
Yes you're right 👍 (I could have edit my PR)

**Pull request merged**
