### PR TITLE
[WIP] Fix empty lines generation during xlf synchronization

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
Please note that this is a WIP where I am trying to add unit tests and try to reproduce the issue.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Did a discovery today: it appears that it might be caused by ```<note from="resx">\n = new line</note>``` in the XLF file. Going to try if this is reproducable.

**Comment by GeertvanHorrik** [comment]
I think I was able to create a reproducable unit test. Will now try to fix the issue (but need to find the cause first).

**Comment by GeertvanHorrik** [comment]
@tom-englert it's ready for review, finally found the reason. The whitespace was preserved when removing a comment via xlf synchronization.

**Comment by tom-englert** [comment]
👍 Thanks!

**Pull request merged**
